export function displayMenu() {
    const contentDiv = document.getElementById('content');
    
    const h1 = document.createElement('h1');
    h1.textContent = "Menu";
    contentDiv.appendChild(h1);

    const entreesDiv = document.createElement('div');
    entreesDiv.id = "entrees";
    const h2Entrees = document.createElement('h2');
    h2Entrees.textContent = "Entrees"
    const entree1Div = document.createElement('div');
    const entree1Name = document.createElement('h3');
    entree1Name.textContent = "Soul Food Special";
    const entree1Description = document.createElement('p');
    entree1Description.textContent = "Crispy fried chicken or tender steak with a side of mac and cheese, collard greens or cabbage, sweet potatoes, and cornbread.";
    entree1Div.append(entree1Name, entree1Description);
    const entree2Div = document.createElement('div');
    const entree2Name = document.createElement('h3');
    entree2Name.textContent = "Spaghetti";
    const entree2Description = document.createElement('p');
    entree2Description.textContent = "Buttery spaghetti noodles, topped or tossed with meat sauce with a side of salad and garlic bread. Served with parmigiano reggiano.";
    entree2Div.append(entree2Name, entree2Description);
    const entree3Div = document.createElement('div');
    const entree3Name = document.createElement('h3');
    entree3Name.textContent = "Thiebou Yapp";
    const entree3Description = document.createElement('p');
    entree3Description.textContent = "Jasmine rice cooked in a savory lamb broth, served with chunks of lamb, onion sauce, boiled egg, and olives, and garnished with bell peppers, cucumber, and tomato.";
    entree3Div.append(entree3Name, entree3Description);
    const entree4Div = document.createElement('div');
    const entree4Name = document.createElement('h3');
    entree4Name.textContent = "Chicken Yassa";
    const entree4Description = document.createElement('p');
    entree4Description.textContent = "Grilled chicken served on a bed of jasmine rice and an onion-mustard sauce with olives.";
    entree4Div.append(entree4Name, entree4Description);
    entreesDiv.append(h2Entrees, entree1Div, entree2Div, entree3Div, entree4Div);
    contentDiv.appendChild(entreesDiv);
    
    const dessertsDiv = document.createElement('div');
    dessertsDiv.id = "desserts";
    const h2Desserts = document.createElement('h2');
    h2Desserts.textContent = "Desserts";
    const dessert1Div = document.createElement('div');
    const dessert1Name = document.createElement('h3');
    dessert1Name.textContent = "Banana Pudding";
    const dessert1Description = document.createElement('p');
    dessert1Description.textContent = "Layers of pudding, butter cookies, and bananas.";
    dessert1Div.append(dessert1Name, dessert1Description);
    const dessert2Div = document.createElement('div');
    const dessert2Name = document.createElement('h3');
    dessert2Name.textContent = "Strawberries and Cream";
    const dessert2Description = document.createElement('p');
    dessert2Description.textContent = "Fresh, ripe strawberries served with a sweet, yougurt cream sauce.";
    dessert2Div.append(dessert2Name, dessert2Description);
    const dessert3Div = document.createElement('div');
    const dessert3Name = document.createElement('h3');
    dessert3Name.textContent = "Thiakry";
    const dessert3Description = document.createElement('p');
    dessert3Description.textContent = "Millet granules in a sweet yogurt sauce with coconut shreds and raisins.";
    dessert3Div.append(dessert3Name, dessert3Description);
    const dessert4Div = document.createElement('div');
    const dessert4Name = document.createElement('h3');
    dessert4Name.textContent = "Crepes";
    const dessert4Description = document.createElement('p');
    dessert4Description.textContent = "Thin pancakes filled with strawberries, bananas, and cream.";
    dessert4Div.append(dessert4Name, dessert4Description);
    dessertsDiv.append(h2Desserts, dessert1Div, dessert2Div, dessert3Div, dessert4Div);
    contentDiv.appendChild(dessertsDiv);
    
    const drinksDiv = document.createElement('div');
    drinksDiv.id = "drinks";
    const h2Drinks = document.createElement('h2');
    h2Drinks.textContent = "Drinks";
    const drink1Div = document.createElement('div');
    const drink1Name = document.createElement('h3');
    drink1Name.textContent = "Bissap";
    const drink1Description = document.createElement('p');
    drink1Description.textContent = "A sweet and tangy hibiscus drink.";
    drink1Div.append(drink1Name, drink1Description);
    const drink2Div = document.createElement('div');
    const drink2Name = document.createElement('h3');
    drink2Name.textContent = "Ginger juice";
    const drink2Description = document.createElement('p');
    drink2Description.textContent = "A spicy ginger and pineapple drink.";
    drink2Div.append(drink2Name, drink2Description);
    const drink3Div = document.createElement('div');
    const drink3Name = document.createElement('h3');
    drink3Name.textContent = "Hot tea";
    const drink3Description = document.createElement('p');
    drink3Description.textContent = "Jasmine tea with ginger and other herbs.";
    drink3Div.append(drink3Name, drink3Description);
    const drink4Div = document.createElement('div');
    const drink4Name = document.createElement('h3');
    drink4Name.textContent = "Water";
    const drink4Description = document.createElement('p');
    drink4Description.textContent = "Still or sparkling water.";
    drink4Div.append(drink4Name, drink4Description);
    drinksDiv.append(h2Drinks, drink1Div, drink2Div, drink3Div, drink4Div);
    contentDiv.appendChild(drinksDiv);
}